import React, { useState } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, Switch } from 'react-native';
import { Calendar, LocaleConfig } from 'react-native-calendars';
import { Clock, CheckCircle, XCircle, Settings } from 'lucide-react-native';
import { ColorPalette } from '../../theme';


const PRIMARY_COLOR = ColorPalette?.primary || '#3B5BFF';
const TEXT_SECONDARY = ColorPalette?.textSecondary || '#94a3b8';

export default function CalendarScreen() {
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  
  const [timeSlots, setTimeSlots] = useState([
    { id: '1', time: '08:00', status: 'available', autoGenerated: true },
    { id: '2', time: '09:00', status: 'booked', client: 'Juan Pérez' },
    { id: '3', time: '10:00', status: 'available', autoGenerated: true },
    { id: '4', time: '11:00', status: 'unavailable', autoGenerated: false },
  ]);

  const toggleStatus = (id) => {
    setTimeSlots(prev => prev.map(slot => 
      slot.id === id ? { ...slot, status: slot.status === 'available' ? 'unavailable' : 'available' } : slot
    ));
  };

  const renderSlot = ({ item }) => (
    <View style={[styles.slotCard, item.status === 'booked' && styles.bookedCard]}>
      <View style={styles.slotInfo}>
        <Clock color={PRIMARY_COLOR} size={18} />
        <Text style={styles.slotTime}>{item.time}</Text>
        {item.autoGenerated && <View style={styles.autoBadge}><Text style={styles.autoText}>Auto</Text></View>}
      </View>
      
      {item.status === 'booked' ? (
        <Text style={styles.bookedText}>{item.client}</Text>
      ) : (
        <View style={styles.actions}>
          <Text style={{color: '#94a3b8', marginRight: 8}}>
            {item.status === 'available' ? 'Visible' : 'Oculto'}
          </Text>
          <Switch
            value={item.status === 'available'}
            onValueChange={() => toggleStatus(item.id)}
            trackColor={{ false: '#334155', true: '#3B5BFF' }}
          />
        </View>
      )}
    </View>
  );

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Gestión de Agenda</Text>
        <TouchableOpacity><Settings color="white" size={24} /></TouchableOpacity>
      </View>

      <Calendar
        theme={{
            backgroundColor: ColorPalette.background,
            calendarBackground: ColorPalette.background,
            textSectionTitleColor: TEXT_SECONDARY,
            selectedDayBackgroundColor: PRIMARY_COLOR,
            selectedDayTextColor: '#000000',
            todayTextColor: PRIMARY_COLOR,
            dayTextColor: '#000000',
            textDisabledColor: '#334155',
            monthTextColor: '#000000',
            arrowColor: PRIMARY_COLOR,
        }}
        style={styles.calendar}
        />

      <View style={styles.slotsHeader}>
        <Text style={styles.slotsTitle}>Horarios para el {selectedDate}</Text>
      </View>

      <FlatList
        data={timeSlots || []}
        keyExtractor={item => item.id.toString()}
        renderItem={renderSlot}
        contentContainerStyle={styles.listContent}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: ColorPalette.background },
  header: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    padding: 20, 
    paddingTop: 40 
  },
  headerTitle: { color: 'black', fontSize: 22, fontWeight: 'bold' },
  calendar: { marginBottom: 10, borderRadius: 15, marginHorizontal: 10 },
  slotsHeader: { padding: 20 },
  slotsTitle: { color: '#94a3b8', fontSize: 14, fontWeight: '600', textTransform: 'uppercase' },
  listContent: { paddingHorizontal: 20, paddingBottom: 20 },
  slotCard: {
    backgroundColor: '#1e293b',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#334155'
  },
  bookedCard: { borderColor: '#3B5BFF33', backgroundColor: '#1e1b4b' },
  slotInfo: { flexDirection: 'row', alignItems: 'center' },
  slotTime: { color: 'white', fontSize: 16, fontWeight: 'bold', marginLeft: 10 },
  autoBadge: { 
    backgroundColor: '#3B5BFF22', 
    paddingHorizontal: 6, 
    paddingVertical: 2, 
    borderRadius: 4, 
    marginLeft: 8 
  },
  autoText: { color: '#3B5BFF', fontSize: 10, fontWeight: '800' },
  bookedText: { color: '#3B5BFF', fontWeight: '600' },
  actions: { flexDirection: 'row', alignItems: 'center' }
});