import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, Switch } from 'react-native';
import { WeekCalendar, CalendarProvider, LocaleConfig } from 'react-native-calendars';
import { Clock, Settings } from 'lucide-react-native';
import { ColorPalette } from '../../theme';
import { useDisponibilidadStore } from '../../apis/coach/useDisponibilidadStore';

// Configuración de idioma
LocaleConfig.locales['es'] = {
  monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
  monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
  dayNames: ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
  dayNamesShort: ['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
};
LocaleConfig.defaultLocale = 'es';

export default function CalendarScreen() {
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const { disponibilidad, getDisponibilidad } = useDisponibilidadStore();

  const onDateChanged = (date) => {
    setSelectedDate(date);
  };

  useEffect(() => {
    getDisponibilidad(selectedDate);
  }, [selectedDate]);

  const renderSlot = ({ item }) => (
    <View style={[styles.slotCard, item.estado === 'ocupado' && styles.bookedCard]}>
      <View style={styles.slotInfo}>
        <Clock 
          color={item.estado === 'ocupado' ? ColorPalette.primary : ColorPalette.textSecondary} 
          size={18} 
        />
        <Text style={[styles.slotTime, item.estado === 'ocupado' && styles.bookedTimeText]}>
          {item.hora_inicio}
        </Text>
        {item.autoGenerated && (
          <View style={styles.autoBadge}>
            <Text style={styles.autoText}>Auto</Text>
          </View>
        )}
      </View>
      
      {item.estado === 'ocupado' ? (
        <View style={styles.clientInfo}>
            <Text style={styles.bookedText}>{item.client || 'Cliente'}</Text>
        </View>
      ) : (
        <View style={styles.actions}>
          <Text style={styles.statusLabel}>
            {item.estado === 'disponible' ? 'Visible' : 'Oculto'}
          </Text>
          <Switch
            value={item.estado === 'disponible'}
            onValueChange={() => {/* Tu lógica de toggle */}}
            trackColor={{ false: ColorPalette.border, true: ColorPalette.primary }}
            thumbColor={'#FFFFFF'}
            ios_backgroundColor={ColorPalette.border}
          />
        </View>
      )}
    </View>
  );

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Gestión de Agenda</Text>
        <TouchableOpacity style={styles.iconButton}>
            <Settings color={ColorPalette.textPrimary} size={22} />
        </TouchableOpacity>
      </View>

      <View style={styles.calendarWrapper}>
        <CalendarProvider 
          date={selectedDate} 
          onDateChanged={onDateChanged}
        >
          <WeekCalendar
            firstDay={1}
            markedDates={{
              [selectedDate]: { selected: true }
            }}
            theme={{
              backgroundColor: ColorPalette.background,
              calendarBackground: ColorPalette.background,
              // Días de la semana
              dayTextColor: ColorPalette.textSecondary,
              textDisabledColor: ColorPalette.border,
              // Día seleccionado
              selectedDayBackgroundColor: ColorPalette.primary,
              selectedDayTextColor: '#FFFFFF',
              // Hoy
              todayTextColor: ColorPalette.accent,
              // Mes y texto
              monthTextColor: ColorPalette.textPrimary,
              textDayFontWeight: '600',
              textMonthFontWeight: '700',
              // Estilo de la "raya" debajo de la semana si la hay
              selectedDotColor: '#ffffff',
            }}
          />
        </CalendarProvider>
      </View>

      <View style={styles.slotsHeader}>
        <Text style={styles.slotsTitle}>Horarios: {selectedDate}</Text>
      </View>

      <FlatList
        data={disponibilidad}
        keyExtractor={item => item.id.toString()}
        renderItem={renderSlot}
        contentContainerStyle={styles.listContent}
        showsVerticalScrollIndicator={false}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: ColorPalette.background },
  header: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
    paddingHorizontal: 20, 
    paddingTop: 60,
    paddingBottom: 20
  },
  headerTitle: { color: ColorPalette.textPrimary, fontSize: 24, fontWeight: '800' },
  iconButton: {
    backgroundColor: ColorPalette.surface,
    padding: 8,
    borderRadius: 12,
  },
  calendarWrapper: {
    height: 120, // Ajuste para el WeekCalendar
  },
  slotsHeader: { paddingHorizontal: 20, marginTop: 20, marginBottom: 15 },
  slotsTitle: { 
    color: ColorPalette.textSecondary, 
    fontSize: 12, 
    fontWeight: '700', 
    textTransform: 'uppercase', 
    letterSpacing: 1 
  },
  listContent: { paddingHorizontal: 20, paddingBottom: 40 },
  slotCard: {
    backgroundColor: ColorPalette.surface,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderRadius: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: ColorPalette.border,
  },
  bookedCard: { 
    borderColor: ColorPalette.primary, 
    backgroundColor: ColorPalette.secondary, // Fondo violeta muy oscuro 
  },
  slotInfo: { flexDirection: 'row', alignItems: 'center' },
  slotTime: { color: ColorPalette.textPrimary, fontSize: 16, fontWeight: '700', marginLeft: 10 },
  bookedTimeText: { color: ColorPalette.textPrimary },
  autoBadge: { 
    backgroundColor: ColorPalette.border, 
    paddingHorizontal: 8, 
    paddingVertical: 2, 
    borderRadius: 6, 
    marginLeft: 10 
  },
  autoText: { color: ColorPalette.accent, fontSize: 10, fontWeight: '800' },
  bookedText: { color: ColorPalette.accent, fontWeight: '700', fontSize: 15 },
  statusLabel: { color: ColorPalette.textMuted, fontSize: 13, marginRight: 10, fontWeight: '500' },
  actions: { flexDirection: 'row', alignItems: 'center' }
});